global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ThinkDocs API metrics
  - job_name: "thinkdocs-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics
    scrape_interval: 30s

  # ChromaDB metrics (if available)
  - job_name: "chromadb"
    static_configs:
      - targets: ["chromadb:8000"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (requires redis_exporter - disabled for now)
  # - job_name: "redis"
  #   static_configs:
  #     - targets: ["redis_exporter:9121"]  # Would need redis_exporter service
  #   scrape_interval: 30s
